#!/bin/bash
sudo rm  /usr/bin/java
sudo ln -s  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java  /usr/bin/java
sudo rm  /Library/Java/Home
sudo ln -s  /Library/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home  /Library/Java/Home
echo "completed symLink."
